name: widget_gen
description: A Flutter Code Gen Package Used to Generate Widgets for WidgetStudio
version: 1.0.0+5
homepage: https://github.com/rodydavis/widget_gen
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  shortid: ^0.1.1
  analyzer: ^0.39.10
  source_gen: ^0.9.5
  build: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  build_version: ^2.0.1

flutter:
  uses-material-design: true
